-- magnitude analysis
-- find the total customer by coutries
SELECT
	country,
	count(distinct customer_key) as no_of_customers
FROM gold.dim_customers
GROUP BY country;
--find the total customers by gender
SELECT
	gender,
	count(distinct customer_key) as no_of_customers
FROM gold.dim_customers
GROUP BY gender;
-- find the total products by category
SELECT
	category,
	count(distinct product_name) as no_of_products
FROM gold.dim_products
GROUP BY category;
-- what is the average cost in each category?
SELECT
	category,
	avg(cost) as avg_cost
FROM gold.dim_products
GROUP BY category; 
-- what is the total revenue generated for each category?
SELECT
	category,
	sum(sales_amount) as total_sales
FROM gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
GROUP BY  category;

-- what is the total revenue generated by each customer
SELECT
	f.customer_key,
	sum(sales_amount) as total_revenue
FROM gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by f.customer_key;

-- what is the distribution of sold items across countries
SELECT
	c.country,
	sum(quantity) as items_sold
FROM gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by c.country;
